import type { PushSubscriptionData } from '@golf/engine';

const VAPID_PUBLIC_KEY = import.meta.env.VITE_VAPID_PUBLIC_KEY as string | undefined;

export function isPushSupported(): boolean {
  return 'serviceWorker' in navigator && 'PushManager' in window && 'Notification' in window && !!VAPID_PUBLIC_KEY;
}

/** Converts the VAPID public key (base64url, as generated by web-push) to the Uint8Array shape PushManager.subscribe expects. */
function urlBase64ToUint8Array(base64Url: string): Uint8Array {
  const padding = '='.repeat((4 - (base64Url.length % 4)) % 4);
  const base64 = (base64Url + padding).replace(/-/g, '+').replace(/_/g, '/');
  const raw = atob(base64);
  return Uint8Array.from(raw, (char) => char.charCodeAt(0));
}

function toSubscriptionData(subscription: PushSubscription): PushSubscriptionData | null {
  const json = subscription.toJSON();
  if (!json.endpoint || !json.keys?.p256dh || !json.keys?.auth) return null;
  return { endpoint: json.endpoint, keys: { p256dh: json.keys.p256dh, auth: json.keys.auth } };
}

/**
 * Gets (or creates) this browser's push subscription. Reuses the existing one if there already
 * is one — subscribing again when already subscribed is a no-op that returns the same
 * subscription instantly, with no new permission prompt. Returns null if push isn't supported,
 * permission isn't granted, or anything about the subscribe call fails (e.g. not actually
 * running as an installed PWA on a platform that requires that).
 */
export async function getOrCreatePushSubscription(): Promise<PushSubscriptionData | null> {
  if (!isPushSupported() || Notification.permission !== 'granted') return null;

  try {
    const registration = await navigator.serviceWorker.ready;
    const existing = await registration.pushManager.getSubscription();
    if (existing) return toSubscriptionData(existing);

    const subscription = await registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY as string) as BufferSource,
    });
    return toSubscriptionData(subscription);
  } catch (err) {
    console.error('Push subscription failed:', err);
    return null;
  }
}
